earthlab/hub-ops

earthhub/values.yaml, staginghub/values.yaml
The trailing `/` turns out to be important.
Change has been deployed.
=> Fix typo in the base URL definition

deploy.py, staginghub/values.yaml
This adds a `--no-setup` flag to `deploy.py` so that you don't have to edit it if you want to run it locally. Running it by hand should be a rare occasion.
This also changes things so that we see more of the command's output for debugging purposes.
=> Make it easier to run `deploy.py` locally

staginghub/requirements.yaml
With the current chart user pods seem to hang when being launched. Or at least the hub things they are hanging.
=> Update staginghub to latest JupyterHub chart

earthhub/values.yaml, staginghub/values.yaml
So far singleuser pods did not request how much memory and CPU they want/need.
=> Fix resource requests for singleuser pods

wshub/values.yaml
https://github.com/thedataincubator/jupyterhub-hashauthenticator doesn't seem to honour the whitelist. Not a big deal as random users would need to know the secret key in order to know their password.
=> Remove user whitelist

wshub/values.yaml
Pulling the singleuser image + starting a new node takes around 5minutes which is exactly what the start timeout is. So for a large fraction of spawns that require a new node things fail because we run into this limit. Increasing the limit to 10m.
An additional thing to investigate is how to speed up pulling the image. How much does running our own docker registry on google cloud cost and does that have a faster network connection to the nodes?
=> Increase start timeout for workshop hub to ten minutes

user-images/wshub/Dockerfile, wshub/values.yaml
This uses rsync to update the data in a user's home directory. With this
we change the behaviour so that:
* if a user edited a data file it will not be overwritten
* if there are new data files in the "source" they will be copied over
What we do not support right now is a file in the source being modified
and then overwrite what the user has in their hme directory. For files
that already exist in the user's home directory that version always
wins. In order to get a new version a user has to explicitly delete the
file they want to update in their home directory, stop their server,
wait for it to stop, start the server again.
=> Change data update behaviour to use rsync

wshub/values.yaml
🌺🌺🌺Hold off merging this until after the workshop is over!🌺🌺🌺
If the target directory doesn't exist rsync will fail. This meant several users at today's workshop didn't get the data in their home directory.
=> Make sure target directory exists before rsync'ing

staginghub/requirements.yaml
The old staginghub chart has the problem where it can't create a new hub because of the pod disruption budget.
=> Update staging hub to a newer chart version

earthhub/values.yaml, outer-edge/values.yaml, staginghub/values.yaml, wshub/values.yaml
This sets resource limits and requests for the various components we have.
By being good at setting limits we can size the part of the cluster that has to be "always on" as small as possible. If we set the limit too low we bump into it, if we set it too high the cluster will be mostly empty. I expect we will have to keep tweaking these for a bit. [Goals](https://makeagif.com/i/wrIfII)
=> Resource limits

staginghub/values.yaml
Answers #80 
User whitelist should be independent of the authentication mechanism.
=> User whitelist

docs/source/day-to-day.rst, docs/source/tooling.rst
Fixes #88 
This adds instructions on how to use git-crypt to decrypt the contents of `secrets/` and who to contact to obtain a copy of the key.
I also had to fix some formatting in `day-to-day.rst`. This was surprising as travis should build the documentation as part of a PR and error on formatting problems.
=> Add information about git-crypt

.travis.yml
This does two things: temporarily remove the bootcamp hub from what travis does as it [fails](https://travis-ci.org/earthlab/hub-ops/builds/411402606#L880) because of the missing secret.
Rewrite how the documentation is built to make sure it actually causes travis to fail when the docs are broken.
=> Temporarily undeploy the bootcamp-hub

user-images/bootcamp-hub/Dockerfile
Adds the missing `Dockerfile` to build a custom docker image for the bootcamp-hub.
=> Add Dockerfile for the custom bootcamp-hub deployment

bootcamp-hub/values.yaml, user-images/bootcamp-hub/Dockerfile
This removes the configuration asking for a custom hub image and adds
nbgitpuller to the user image Dockerfile for the bootcamp-hub.
=> Remove config asking for custom hub, add nbgitpuller

.travis.yml
What might be happening is that we don't checkout enough of the history to work out what the correct tag is to use for the image. Which causes https://travis-ci.org/earthlab/hub-ops/builds/413659311?utm_source=github_status&utm_medium=notification to fail because it determines a too recent commit as the tag to use.
Travis docs: https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth
=> Use infinite clone depth on travis

tools/README.md, tools/pin-cluster.yaml, tools/scale-cluster.yaml
These two snippets allow us to force the cluster to scale up and then stop it from scaling down again. This is useful to provision some spare capacity ahead of a workshop/class starting.
It requires manual supervision and undoing once you do not need it any more as the provisioned virtual machines/nodes will not be removed again until you say so. This means they will keep costing you money if you forget to turn this off again.
cc @lwasser
=> Add forced cluster scaling snippets

bootcamp-hub/requirements.yaml, user-images/bootcamp-hub/Dockerfile
This brings the bootcamp hub to JupyterHub v0.9.2. The main benefit of this update is that the newer JupyterHub can restart itself if too many consecutive spawns failed. This is a bandaid for the real problem that sometimes the JupyterHub spawner loses track of what pods are starting/running/finished. It manifests itself in a user logging in to the hub, their pod starts up but JupyterHub never notices and keeps the user waiting for ever. The "fix" for this behaviour is to restart the hub manually. With the latest version of jupyterhub the hub restarts itself if there are five consecutive launch failures.
=> Update bootcamphub to newer jupyterhub version

outer-edge/README.md, outer-edge/values.yaml
Update our version of kube-lego to fix #133 
Now certificates should get renewed in time.
=> Fix certificate renewal process

.travis.yml, deploy.py, docs/source/day-to-day.rst
This hub is from a course in July 2018 and no longer needed. PR does not delete the information about the hub, simply removes the build from travis.
=> Remove bootcamp hub

hub-charts/ea-hub/values.yaml, user-images/README.md, user-images/ea-hub/Dockerfile
I think this should in theory add [nbgitpuller](https://jupyterhub.github.io/nbgitpuller/install.html#install) back 
i really like using nbgitpuller in the hub and don't want to remove it unless we think using good old git is equally useful. it is a very nice tool and worked well as it just always synced things automagically.
this also tries to remove layers by merging run statements
=> Add nbgitpuller back to the hub

hub-charts/ea-hub/values.yaml
@lwasser This PR updates the repository and directory name for the homework template. The repository is a public repository created to get the homework templates onto the hub.  Fixes #175
=> Update homework template repo for EA Bootcamp in ea-hub/values.yaml

hub-charts/staginghub/requirements.yaml, hub-charts/staginghub/values.yaml, user-images/staginghub/Dockerfile
This updates the hub-charts and user-images in staginghub to be the same as ea-hub. Then, we can use staginghub as a first step of deploying changes, check that everything is working, and then update ea-hub to match.
=> Update staginghub to match ea-hub

hub-charts/ea-hub/values.yaml
@lwasser @kcranston This PR updates the GitHub usernames for the EA Python course.
After Wed 1/22 (last of registration), there may be a few more names that will be removed, but this is a good start to the clean up.
=> Update EA Python students in ea-hub/values.yaml

hub-charts/ea-hub/values.yaml
@lwasser This PR removes students who are not actively enrolled in the EA Python course at this time (toastferry will receive an incomplete for this course at the end of the semester).
=> Remove students not in EA Python course

user-images/ea-hub/Dockerfile
This got removed [here](b7daf7bbf7db7452dcb9e0d668dedd2895a5c125)  but we need it to be able to download files. it's funny because i thought we had this functionality and then it disappeared. going to do some more testing but this should work for our class.
=> add nbzip back to the hub

hub-charts/ea-hub/values.yaml
this is trying to address #205 
it's a hack that if there is no space, then it will continue to launch the pod without gitpuller
=> not sure if this syntax is correct -- tryin || 

.travis.yml, hub-charts/staginghub/requirements.yaml, hub-charts/staginghub/values.yaml, user-images/staginghub/Dockerfile
Updating the jupyterhub helm chart for the staging hub. The latest version includes [this commit](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/commit/61cf357992f605a6a0e18e7dd27d404f34ec5315) which addresses the warning we are seeing in travis. I have no idea if this will fix things, but this PR does not affect ea-hub, so it seems safe.
=> Update version of jupyter hub helm chart on staginghub

.travis.yml, deploy.py, user-images/staginghub/Dockerfile
As discussed in #223, separate the build & push steps from the deploy steps so that these run as different python processes. Should make it easier to see when things fail / timeout. 
Also removed the references to building hub-images, as that whole directory got removed with PR #221
=> Separate build & push from deploy

deploy.py, user-images/edsc-hub/Dockerfile
some weird things are happening in the build now.
It seems like it's trying to pull an image that doesnt exist? or there are several tags and i'm not sure why there are several tags that it's trying. 
https://travis-ci.org/github/earthlab/hub-ops/jobs/701861190#L284 
when i go to docker that build is clearly not there so i'm not sure why it's trying to pull it. 
https://travis-ci.org/github/earthlab/hub-ops/jobs/701861190#L286
https://travis-ci.org/github/earthlab/hub-ops/jobs/701861190#L716
but i *don't think it pushes to dockerhub as its not on dockerhub and i never see a push. 
it seems to me that in a PR -- the hub should
1. build the new image fully and push to docker hub if it's successful (i think??) 
2. Then stop before releasing new things to GC  via helm etc.
i may not …
=> update the ea envt to the most recent docker build

hub-charts/edsc-hub/values.yaml
this should create a new dir for gitpuller files. it should fix the hanging issue we are seeing now.
this addresses #255 .. it's a hack but we need the hub to be accessible this week!!
=> this will just change the gitpuller location

hub-charts/staginghub/values.yaml
This is an attempt to modify the bash command in the postStart lifecycleHook so that the pod continues to deploy even if gitpuller fails. Only changed on staginghub in this PR.
=> modify poststart hook to fail gracefully

user-images/ea-hub/Dockerfile, user-images/staginghub/Dockerfile
this should fix 
1. the download button issue not working - adds zip to the ea hub image
2. removes the python wrapper from gitpuller command on staging hhub which is breaking every build
#272 #276 
ive tested both builds locally and they seem to work!
=> Fix download button & fix staging hub build

user-images/nbgrader-hub/Dockerfile
this relates to https://github.com/jupyter/nbgrader/issues/1306 
we are running into some really odd formgrader and feedback issues ... i noticed that nbgrader has traitlets and nbconvert pinned. downgrading locally did work for me. it's hard to test this on the hub because you can't restart the entire hub envt without shutting down the pod and then the image rebuilds (negating any changes you've made)...
=> force downgrade of nbconvert and traitlets

deploy.py
It looks like the --force flag with this version of helm is problematic and causing failures about trying to change immutable objects. Seeing if removing it fixes the failing deployment.
=> remove force flag from helm in deploy.py

hub-configs/ea-hub.yaml, hub-configs/nbgrader-hub.yaml
By default, the nginx ingress has a 1mb limit for upload. We need more to be able to upload data files.
=> Increase nginx body-size

.github/workflows/build-only.yml
This update the GitHub Actions so that on a pull request, we check that the docker image builds, but we do not push to Dockerhub. This means that PR builds do not need access to repository secrets and can be successfully built from forks. 
Addresses #327
=> on PRs, build image but do not push

hub-configs/ea-hub.yaml, hub-configs/nbgrader-hub.yaml
Two changes here:
* increases the length of time before the spawning of a user pod times out
* add [user placeholders](https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/optimization.html?highlight=timeout#scaling-up-in-time-user-placeholders) to reduce the time to spawn a new node
=> reduce timeout failures when starting user pods

hub-charts/ea-hub/values.yaml
Gitpuller is having issues so pushing up a temporary work around.
=> Temporarily removing lifecycle hooks to get around a gitpuller issue.

.github/workflows/build-deploy.yml
There was one more instance of nbgrader-hub in the github actions workflow. This PR removes it.
=> remove one final instance of nbgrader-hub from actions
