earthlab/hub-ops

README.md, earthhub/requirements.lock, monitoring/requirements.lock, staginghub/requirements.lock
=> A bump to wake up travis

earthhub/values.yaml, wshub/values.yaml
=> Fix memory limits

user-images/wshub/Dockerfile, wshub/values.yaml
Download the data when the image is built. Then use a lifecycle hook to move it to the user's home directory.
=> [WIP] Add data download command

wshub/values.yaml
Follow up to #55 to add missing semicolon.
A reason to invest in #23
=> Don't forget them semicolons

docs/source/day-to-day.rst, docs/source/index.rst, docs/source/tooling.rst
Leave no trace!
These are instructions for how to remove a hub once you are done with it.
Closes #11
=> Add instructions for removing a hub

staginghub/values.yaml
Fixes #69 which was not a complete PR.
How can we prevent errors like this in the future?
=> Need to reference custom image

staginghub/values.yaml
=> Actually start using whitelist

.travis.yml, bootcamp-hub/Chart.yaml, bootcamp-hub/requirements.yaml, bootcamp-hub/values.yaml, deploy.py, docs/source/authentication.rst, docs/source/day-to-day.rst
Ok @betatim here is my initial attempt at setting up a new hub. I have a series of questions about this process here that i started to collect:
https://github.com/earthlab/hub-ops/issues/72 
Also note i'm updating the docs as i go just to ensure i understand in the future !!! please comment away and i'll update as needed. I am not sure still have to add authentication to this hub. Also unsure about the data part. IE the workshop had data attached to it. we don't NEED to have data for this setup. but i do want an earth-analytics/data directory (i think). @jlpalomino do you want to have the data dir setup for them? OR do you want them to be able to create it in BASH?! that could be a nice activity but i don't remember what you have planned for day 1. 
@betatim  also do i have to BUILD the …
=> Adding New hub called bootcamp-hub 

bootcamp-hub/values.yaml
i suspect the admin info may be incorrect so removing for the time beigin.
=> remove admins from list

bootcamp-hub/values.yaml
here i try to add both whitelist users AND admins.. but i'm still not convinced i'm adding admins correctly.
=> adding whitelist users AND admins

bootcamp-hub/values.yaml
This adds Leah and Tim to the whitelist and to the admin list.
=> Add some users to the bootcamp whitelist and admin list

docs/source/day-to-day.rst
Make a start on documenting day-to-day cluster operation tools.
=> Operations docs

bootcamp-hub/values.yaml, ea-hub/values.yaml, staginghub/values.yaml, wshub/values.yaml
Reduce guaranteed memory for the botocamp-hub jupyterhub pod.
=> Lower bootcamp hub memory

bootcamp-hub/values.yaml, ea-hub/values.yaml, monitoring/values.yaml, outer-edge/README.md, staginghub/values.yaml, wshub/values.yaml
Stop core pods from running on the user pool.
=> Add node selectors for the core pods

deploy.py
=> Fix deploy script so it treats the monitoring chart differently

hub-charts/ea-hub/values.yaml
setting up this PR so i can merge it once travis does it's thing!
=> adding whitelist members to ea-hub

user-images/ea-hub/Dockerfile
=> Ea hub - envt update

hub-charts/ea-hub/values.yaml
This should fix the error with saving notebooks over 1MB in size.
=> Increase proxy body size

user-images/ea-hub/Dockerfile
more updates including the most recent data download.
=> Updates to earthpy

user-images/ea-hub/Dockerfile
Lets use the super new notebook UI that gives feedback when uploading something.
=> Use cutting edge notebook to get UI improvement

user-images/ea-hub/Dockerfile
new docker build of updated envt
=> Fix for gdal rasterio issue -- libkea for lyft

hub-charts/ea-hub/values.yaml
@lwasser This pull request updates the list of GitHub users in hub-charts/ea-hub/values.yaml to reflect the Earth Analytics Application course enrollment.
=> Update GitHub user access list

hub-charts/nbgrader-hub/requirements.yaml, hub-charts/nbgrader-hub/values.yaml, user-images/nbgrader-hub/Dockerfile
Reverts earthlab/hub-ops#151 because nbgrader-hub deployment failing.
=> Revert "new versions of things for nbgrader hub"

README.md, hub-charts/nbgrader-hub/requirements.yaml, hub-charts/nbgrader-hub/values.yaml, user-images/nbgrader-hub/Dockerfile
These changes re-incorporate the reverted PR #151
=> Nbgrader updates take2

hub-charts/ea-hub/values.yaml, user-images/nbgrader-hub/Dockerfile
Switch `jupyterlab` installation to conda / conda-forge rather than pip to see if this resolves dependency issues with `jupyter-console`  and `prompt_toolkit`.
=> Jupyterhub conda

user-images/ea-hub/Dockerfile
This updates the hub to the version of the ea env that users nbgrader 0.6.0
=> update ea env to latest

hub-charts/ea-hub/values.yaml
testing if this is case sensitive
=> updating student list

hub-charts/ea-hub/values.yaml
@lwasser This PR removes two students who are currently waitlisted for the graduate section: lucap1211 and ccassisi.  It also adds a new certificate student who emailed me this morning: annapav7.  Fixes #171 
Note that superneyo is a certificate student who has not yet completed enrollment. Lauren has been working with this person and believes that they will enroll soon. If this does not happen by the enrollment deadline, I will submit another PR to remove this person.
=> Update ea-hub/values.yaml with current Bootcamp enrollment

deploy.py
this addresses #179  essentially hubops is an org which allows us all to manage it. I just created an earth lab user that we can use for deployment. password should be solid. let's see if this works!
=> update deployment username - password should work

hub-charts/ea-hub/values.yaml
@lwasser This PR add another certificate student (toastferry) to ea-hub/values.yaml.
=> Add another certificate student to ea-hub

hub-charts/ea-hub/values.yaml
@lwasser This PR adds two new GitHub usernames for students in the bootcamp course and removes one student who is no longer enrolled in the course.
=> Update bootcamp students in ea-hub/values.yaml

user-images/ea-hub/Dockerfile, user-images/staginghub/Dockerfile
I thought i had addressed this update, but it looks like i pinned the incorrect envt version
=> Fix ea envt version 

user-images/ea-hub/Dockerfile
@lwasser This PR updates user-images/ea-hub/Dockerfile for the ea-hub with the latest build (latest version of matplotcheck 0.0.11).
=> Update matplotcheck in ea-hub

.travis.yml, deploy.py
@lwasser I think this may solve the issues you face, which I'm quite confident was caused by a purely numerical git hash being set in a yaml file, that suddenly interpreted the value as an integer rather than a string.
=> Fix deploy and update helm/kubectl

.travis.yml
I bumped this to a version that didn't exist yet, 1.18.2 does though.
=> Fix kubectl version

user-images/ea-hub/Dockerfile
Trying to add the improved version of nbzip
https://github.com/ryanlovett/jupyter-tree-download
=> Nbzip add back

.travis.yml
=> redeploy staging hub

docs/source/daily-operations/modify-remove-hub.rst
Adding notes from @betatim about how the admin panel works. Thank you again Tim!!
=> document admin panel

hub-charts/ea-hub/requirements.yaml
=> update ea-hub to new version of jhub chart

hub-charts/edsc-hub/values.yaml
@lwasser This PR adds the new HDR users through row 17 in the GitHub user name spreadsheet.
=> Add first round of HDR users

hub-charts/edsc-hub/values.yaml
@lwasser This PR adds the new HDR users through row 23 in the GitHub user name spreadsheet.
=> Add second round of HDR users

hub-charts/edsc-hub/values.yaml
@lwasser This PR adds a few new users based on requests from Python Data 101 Workshop attendees.
=> Add new HDR users from Python Data 101 Workshop Day

hub-charts/edsc-hub/values.yaml
hoping this should fix the download file issues. not sure how the hubs ended up with diff allocations!
=> increase mem allocation on edsc hub

outer-edge/README.md
I've migrated from kube-lego to cert-manager and put notes about what I did in the outer-edge/README. These instructions address #190
=> add notes on cert-manager migration

deploy.py
Deploy script tested locally. No syntax errors, but helm is timing out :(
=> fix undefined tag variable

deploy.py
Fixed issue with deploy scrip when image already exists. Addresses #249 
Also added some more logging statements to the deploy script that should make it easier to tell what's going on.
=> Move tag inside conditional

user-images/staginghub/Dockerfile
THIS PR updates the envt to match the most current ea envt that contains earthpy 0.9.2 
testing the entire build with this prior to messing with the edsc hub
=> staging hub: update envt - test prior to messing w edsc 

.travis.yml, docs/source/daily-operations/modify-remove-hub.rst
we can restart it again in august
also made some minor doc edits here just for the future.
The one piece i'm still struggling with is that travis user being my local user. i can't seem to get rid of it. but otherwise the hub is GONE as is all storage and this PR can be merged i think!
=> Shutdown eahub

hub-charts/edsc-hub/values.yaml
Removed jenny from admin role and added myself
=> Add Nathan as Hub Admin

deploy.py
Version of `deploy.py` before I modified it to add the python gitpuller wrapper script to the docker build.
=> revert to previous version of deploy script 

hub-charts/ea-hub/values.yaml
Added student github names so they can access the jupyter hub this semester.
=> Add students for upcoming semester

.travis.yml, hub-charts/ea-hub/values.yaml
i just shut down the edsc hub so ensuring that it doesn't get redeployed
=> update from master

hub-charts/ea-hub/values.yaml
Added a missing student to the jupyter hub!
=> Added one student

.travis.yml, deploy.py, user-images/ea-hub/Dockerfile, user-images/staginghub/Dockerfile
just for the time being. also i didn't fully turn off the edsc hub so fixin that as well.
=> Stop staging hub deployment

hub-charts/ea-hub/values.yaml
Adding @nquarder to have hub access!
=> added nate to the repo

deploy.py
This code tested and working on staging. I want this on master before we move over nbgrader-hub.
=> check that image exists if we don't think it needs rebuilding

CONTRIBUTING.rst, docs/source/daily-operations/deployment-workflow.rst, docs/source/daily-operations/hub-monitoring.rst, docs/source/daily-operations/manage-storage.rst, docs/source/daily-operations/modify-remove-hub.rst, docs/source/daily-operations/new-hub.rst
This is the last step for #285
=> Update deployment docs with new staging branch info

hub-charts/climate-hub/values.yaml
Adding myself to the climate workshop hub so I can help with debugging
=> add karen to climate hub

hub-charts/climate-hub/values.yaml
=> added student

.travis.yml
all has been shut down locally. this just stops travis from rebuilding
=> stop building climate hub

hub-charts/nbgrader-hub/values.yaml
I think we need to add this hub too monitoring but i'm not sure how to do that right now.
=> ram update

hub-charts/ea-hub/values.yaml
Updated the ea-hub values with the github usernames for the spring course! @lwasser
=> Usernames for spring course

hub-charts/ea-hub/values.yaml, hub-configs/ea-hub.yaml
Put the names in the right place this time @lwasser
=> 2021 spring names 2

user-images/ea-hub/Dockerfile, user-images/nbgrader-hub/Dockerfile
Updated to lastest environment
=> Updated to latest earth-analytics-python-env

user-images/ea-hub/Dockerfile
Updating ea-hub to match nbgrader-hub environment
=> EA-hub env update

user-images/ea-hub/Dockerfile, user-images/nbgrader-hub/Dockerfile
Update nbgrader hub and ea hub to latest docker tag for the environment.
=> updated to latest envt image

hub-charts/ea-hub/values.yaml
=> remove students not in the applications course

.github/workflows/build-deploy.yml, .github/workflows/build-only.yml, docs/source/daily-operations/modify-remove-hub.rst
=> remove grading hub

hub-charts/ea-hub/values.yaml
increased storage from 12 to 15 gb
=> Increased storage

hub-configs/ea-hub.yaml
Removing the gitpuller dependency from the config file for the ea hub.
=> Removing lifecycle hooks from config
